version: '3'
services:
    minecraft:
        build: 
            context: .
            args: 
                - SERVER_URL=https://launcher.mojang.com/v1/objects/35139deedbd5182953cf1caa23835da59ca3d7cd/server.jar
        container_name: mcserver
        environment:
            - EULA=true
        ports:
            - 25565:25565
        volumes: 
            - mcserver-data:/minecraft/data

volumes:
    mcserver-data: