version: '3'
services:
    minecraft:
        build: .
        container_name: mcserver
        environment:
            - EULA=true
        ports:
            - 25565:25565
        volumes: 
            - mcserver-data:/minecraft/data

volumes:
    mcserver-data: